// Generated by scripts/build-signals-rss.mjs. Do not edit by hand.
// Daily Signal source data lives in public/signals/*.json.

export const bundledSignalIndex = [
  {
    "slug": "2026-06-25-autonomous-agents-redraw-career-value",
    "date": "2026-06-25",
    "title": "Autonomous Agents Redraw Career Value",
    "pattern": "The five stories point to a labor market learning two truths at once: agents are becoming infrastructure, and careers now have to outlast any one employer's redesign. Oracle cuts and broader tech restructuring show old roles being rewritten, while PwC and the 100-year career frame point to renewal rather than simple replacement. The durable move is to build portable judgment, not just defend a job title.",
    "stages": [
      "Unhook Identity",
      "Discover AI's Power",
      "Reclaim Value"
    ],
    "imageUrl": "https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2026/06/John-Roese3.jpg"
  },
  {
    "slug": "2026-06-24-entry-level-jobs-get-senior-ai-standards",
    "date": "2026-06-24",
    "title": "Entry-Level Jobs Get Senior AI Standards",
    "pattern": "The early-career bargain is being compressed. Entry-level workers are now expected to bring senior judgment while schools, governments, and HR teams race to explain a labor market where AI both threatens roles and creates new ones. The real signal is not 'learn a tool'; it is that people need purpose, adaptability, and proof of value before the first rung appears.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Find Your Purpose"
    ],
    "imageUrl": "https://www.computerworld.com/wp-content/uploads/2026/06/4188067-0-04562000-1782298982-future-ready-IT-workforce-shutterstock_2677450619.jpg?quality=50&strip=all&w=1024"
  },
  {
    "slug": "2026-06-23-microsoft-job-fear-meets-oracle-cuts",
    "date": "2026-06-23",
    "title": "Microsoft Job Fear Meets Oracle Cuts",
    "pattern": "Today's stories split the AI transition between fear and agency: students worry about jobs, Oracle cuts roles, and AI begins shaping even how young people discover universities. At the same time, Picsart's creator economy story shows value moving toward people who can claim audience, voice, and leverage. Purpose formation now has to happen earlier and more deliberately than the old career path required.",
    "stages": [
      "Unhook Identity",
      "Find Your Purpose",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://images.moneycontrol.com/static-mcnews/2026/04/20260401082814_MixCollage-01-Apr-2026-01-53-PM-7018.jpg"
  },
  {
    "slug": "2026-06-22-ai-moves-into-the-workday",
    "date": "2026-06-22",
    "title": "Job Fear Meets AI Education",
    "pattern": "The day's pattern is work identity moving into systems design. AI agents are getting identities and access, leaders are comparing AI to an industrial revolution, and education voices are telling students their fear is rational. The human answer is not panic or blind optimism; it is building AI fluency around human-centered judgment before institutions redesign the roles.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Find Your Purpose",
      "Discover AI's Power"
    ],
    "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a3908e60d0b184acc61cf8a/0x0.jpg?format=jpg&crop=4048,2275,x0,y0,safe&height=900&width=1600&fit=bounds"
  },
  {
    "slug": "2026-06-21-ai-moves-into-the-workday",
    "date": "2026-06-21",
    "title": "AI Agents Get Work Identities",
    "pattern": "AI is becoming a coworker with credentials, permissions, and practical reach, while companies keep using AI language to explain job cuts. That makes the old question 'will AI replace me?' too narrow. The better question is what human voice, accountability, and creative judgment become more valuable when agents can take on more of the work.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://memeburn.com/wp-content/uploads/2026/06/NewCore-Raises-66M-To-Give-AI-Agents-Work-Identities-In-2026-1024x576.png"
  },
  {
    "slug": "2026-06-20-agents-enter-the-real-economy",
    "date": "2026-06-20",
    "title": "Agents Enter The Real Economy",
    "pattern": "AI is moving from answer machine to active participant. That makes the old productivity frame too small. The question becomes who directs the work, what judgment remains human, and where people learn to create with systems instead of merely using tools.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://www.digitaltrends.com/tachyon/2026/06/AdobeStock_567681994.jpg?resize=1200%2C630"
  },
  {
    "slug": "2026-06-19-ai-moves-into-the-workday",
    "date": "2026-06-19",
    "title": "AI Education Meets The Work Shift",
    "pattern": "Education and work are both being forced to move from compliance to capability. AI is turning cheating, coding, creative production, and email delegation into tests of whether people understand the systems they use, not just whether they can produce output. AI literacy is becoming protective value: people who can direct the tool thoughtfully are less exposed than people who only perform the old task.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Find Your Purpose",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://s.hdnux.com/photos/01/66/47/07/31093195/3/rawImage.jpg"
  },
  {
    "slug": "2026-06-18-ai-moves-into-the-workday",
    "date": "2026-06-18",
    "title": "AI Literacy Becomes The Baseline",
    "pattern": "AI literacy is crossing from advantage to baseline. Government hiring, graduate roles, creator work, and layoff narratives all point to the same shift: execution is easier, but trusted judgment, voice, and direction are harder to replace. Treat AI fluency as table stakes and human point of view as the real differentiator.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Find Your Purpose",
      "Start Creating"
    ],
    "imageUrl": "https://cdn.govexec.com/media/img/cd/2026/06/17/NGA_AOP_image_1-1/open-graph.png"
  },
  {
    "slug": "2026-06-16-ai-moves-into-the-workday",
    "date": "2026-06-16",
    "title": "AI Agents Need Human Control",
    "pattern": "This issue is about control: agents are becoming capable enough to touch real systems, while companies are still using AI as a blunt story for cuts. The strongest human response is not to compete task-for-task, but to design clearer delegation, constraints, voice, and accountability. AI can multiply output; it cannot decide what deserves trust unless people stay in command.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://www.computerworld.com/wp-content/uploads/2026/06/4185559-0-48713800-1781610470-youtube-thumbnail-uPpd9EJ4iNI_55eb26.jpg?quality=50&strip=all&w=1024"
  },
  {
    "slug": "2026-06-13-ai-lays-off-america-while-apple-launches-siri",
    "date": "2026-06-13",
    "title": "AI Lays Off America While Apple Launches Siri",
    "pattern": "AI is no longer the future of work — it's the present reason people are losing it. But the people who thrive will be those who treat AI as a collaborator, not a replacement. The Great Repurpose isn't a luxury anymore; it's a survival skill.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Find Your Purpose",
      "Start Creating"
    ],
    "imageUrl": "https://media.assettype.com/outlookbusiness/2026-04-24/zfplh735/5.png?w=1200&ar=40%3A21&auto=format%2Ccompress&ogImage=true&mode=crop&enlarge=true&overlay=false&overlay_position=bottom&overlay_width=100"
  },
  {
    "slug": "2026-06-07-ai-reshapes-work-identity-and-creativity",
    "date": "2026-06-07",
    "title": "AI Reshapes Work, Identity, And Creativity",
    "pattern": "The signal is that AI is no longer only changing what people do. It is changing how people understand themselves, how companies explain job cuts, and where creative value lives. The human move is to name the part of us that remains durable before the market names us obsolete.",
    "stages": [
      "Reclaim Value",
      "Unhook Identity",
      "Find Your Purpose",
      "Start Creating"
    ],
    "imageUrl": "https://gcp-na-images.contentstack.com/v3/assets/bltea6093859af6183b/blt7f9b16d39bc44ab3/6a22353270c5a9918127c424/AI-Changing-Human.jpg?branch=production&width=1200&quality=75&auto=webp&crop=1200:675&height=675"
  },
  {
    "slug": "2026-06-05-creative-control-in-the-age-of-ai",
    "date": "2026-06-05",
    "title": "Creative Control In The Age Of AI",
    "pattern": "The old guard of creative ownership is fighting back. Adobe's Creator Act, the creator economy conversation, and the rise of AI agents all point to the same inflection point: human creators are demanding legal, technical, and economic guardrails over their work. The Great Repurpose is not just about adapting to AI. It is about asserting who owns the output and who gets to decide.",
    "stages": [
      "Reclaim Value",
      "Start Creating",
      "Discover AI's Power",
      "Unhook Identity"
    ],
    "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a20a739ac75b76282f7cc99/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds"
  },
  {
    "slug": "2026-06-04-daily-tgr-signal",
    "date": "2026-06-04",
    "title": "Creativity Moves Upstream",
    "pattern": "The signal is that creativity is becoming more valuable, not less, but it is changing location. As AI absorbs more execution, human advantage moves upstream into taste, judgment, problem selection, and the courage to make something that actually matters.",
    "stages": [
      "Reclaim Value",
      "Unhook Identity",
      "Find Your Purpose",
      "Start Creating",
      "Discover AI's Power"
    ],
    "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a11204aa488ec8b473b57df/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds"
  }
] as const;

export const bundledSignalsBySlug = {
  "2026-06-25-autonomous-agents-redraw-career-value": {
    "slug": "2026-06-25-autonomous-agents-redraw-career-value",
    "date": "2026-06-25",
    "title": "Autonomous Agents Redraw Career Value",
    "pattern": "The five stories point to a labor market learning two truths at once: agents are becoming infrastructure, and careers now have to outlast any one employer's redesign. Oracle cuts and broader tech restructuring show old roles being rewritten, while PwC and the 100-year career frame point to renewal rather than simple replacement. The durable move is to build portable judgment, not just defend a job title.",
    "stages": [
      "Unhook Identity",
      "Discover AI's Power",
      "Reclaim Value"
    ],
    "imageUrl": "https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2026/06/John-Roese3.jpg",
    "stories": [
      {
        "title": "Autonomous agents are redefining work and jobs - SiliconANGLE",
        "url": "https://siliconangle.com/2026/06/24/dell-ai-autonomous-agents-jobs-aifactoriesdatacenters/",
        "source": "siliconangle.com",
        "published": "2026-06-24T15:31:02+00:00",
        "summary": "Dell's AI work points to a practical shift: autonomous agents are moving from demo layer into the operating model of companies. That matters because job design, capital spending, and human leverage start changing once agents can take on pieces of real enterprise work.",
        "imageUrl": "https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2026/06/John-Roese3.jpg",
        "stages": [
          "Discover AI's Power",
          "Unhook Identity"
        ],
        "keyPoints": [
          "Dell is framing autonomous agents as part of the next enterprise infrastructure shift, not just another software feature.",
          "The story connects AI agents to job design and the economics of AI factories and data centers.",
          "For TGR, the useful move is learning what work agents can absorb while naming the human judgment that still has to steer them."
        ]
      },
      {
        "title": "Why The 100-Year Career Will Change How Employers Think About Work",
        "url": "https://www.forbes.com/sites/benjaminlaker/2026/06/24/why-the-100-year-career-will-change-how-employers-think-about-work/",
        "source": "forbes.com",
        "published": "2026-06-24T04:59:00+00:00",
        "summary": "The 100-year career idea makes the AI transition bigger than a single reskilling cycle. Longer lives and faster capability shifts mean people and employers have to design for renewal, adaptability, and portable value instead of one stable ladder.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a3b99037338d7f370b94acf/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Unhook Identity",
          "Reclaim Value"
        ],
        "keyPoints": [
          "Longer working lives make career sustainability a structural question for employers.",
          "AI disruption turns adaptability from a nice trait into career infrastructure.",
          "For TGR, the story reinforces that identity has to separate from the current job wrapper."
        ]
      },
      {
        "title": "Oracle layoffs: Tech giant cuts 21,000 jobs as AI investments reshape workforce- Moneycontrol.com",
        "url": "https://www.moneycontrol.com/technology/oracle-layoffs-tech-giant-cuts-21-000-jobs-as-ai-investments-reshape-workforce-article-13956730.html",
        "source": "moneycontrol.com",
        "published": "2026-06-23T02:58:00+00:00",
        "summary": "Oracle's reported job cuts make the workforce redesign story concrete. When a company realigns around AI at this scale, the risk is not only job loss; it is the speed at which old roles stop explaining where human value belongs.",
        "imageUrl": "https://images.moneycontrol.com/static-mcnews/2026/04/20260401082814_MixCollage-01-Apr-2026-01-53-PM-7018.jpg",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "Oracle reportedly cut around 21,000 jobs globally over the past year while investing heavily in AI.",
          "The story shows AI strategy turning into organizational redesign, not just tool adoption.",
          "For TGR, the practical question is what value a person can carry when the company rewrites the org chart."
        ]
      },
      {
        "title": "PwC chairman pushes back on fears of AI-driven mass layoffs, says AI is adding more jobs",
        "url": "https://indianexpress.com/article/technology/artificial-intelligence/pwc-chairman-pushes-back-on-fears-of-ai-driven-mass-layoffs-says-ai-is-adding-more-jobs-10753088/",
        "source": "indianexpress.com",
        "published": "2026-06-23T07:19:18+00:00",
        "summary": "PwC's chair gives the counter-signal to the layoff narrative: effective AI adoption can also expand work and productivity. The tension matters because workers still have to repurpose themselves while leaders argue over whether AI subtracts jobs or redesigns them.",
        "imageUrl": "https://images.indianexpress.com/2026/06/PwC-chairman-quells-fears-of-AI-driven-mass-layoffs-says-AI-adoption-is-adding-more-jobs.png",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "PwC's Mohamed Kande says organizations using AI well are focused on transformation and productivity gains.",
          "The claim complicates the simple story that AI adoption automatically means mass layoffs.",
          "For TGR, the stable takeaway is that people need portable value whether AI shrinks roles or expands them."
        ]
      },
      {
        "title": "Oracle AI Layoffs, Meta Workforce Cuts, Amazon Restructuring, Microsoft Workforce Changes Signal Global Tech Downsizing Wave in 2026",
        "url": "https://www.ibtimes.sg/oracle-ai-layoffs-meta-workforce-cuts-amazon-restructuring-microsoft-workforce-changes-signal-88452",
        "source": "ibtimes.sg",
        "published": "2026-06-24T09:13:51+00:00",
        "summary": "The broader tech downsizing story turns isolated layoff headlines into a pattern. AI investment, restructuring, and pressure for efficiency are converging across major companies, which makes repurposing a near-term workforce problem rather than an abstract future concern.",
        "imageUrl": "https://data.ibtimes.sg/en/full/87335/tech-layoffs.jpg?w=1200&h=630?q=60",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "The article frames Oracle, Meta, Amazon, and Microsoft workforce changes as part of a wider 2026 tech downsizing wave.",
          "AI investment is becoming one of the forces companies cite as they restructure teams.",
          "For TGR, the story sharpens the need to build identity and value outside any single employer's operating plan."
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-24-entry-level-jobs-get-senior-ai-standards": {
    "slug": "2026-06-24-entry-level-jobs-get-senior-ai-standards",
    "date": "2026-06-24",
    "title": "Entry-Level Jobs Get Senior AI Standards",
    "pattern": "The early-career bargain is being compressed. Entry-level workers are now expected to bring senior judgment while schools, governments, and HR teams race to explain a labor market where AI both threatens roles and creates new ones. The real signal is not 'learn a tool'; it is that people need purpose, adaptability, and proof of value before the first rung appears.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Find Your Purpose"
    ],
    "imageUrl": "https://www.computerworld.com/wp-content/uploads/2026/06/4188067-0-04562000-1782298982-future-ready-IT-workforce-shutterstock_2677450619.jpg?quality=50&strip=all&w=1024",
    "stories": [
      {
        "title": "Entry-level AI workers now need 'senior-level' skills, PwC says",
        "url": "https://www.computerworld.com/article/4188067/entry-level-ai-workers-now-need-senior-level-skills-pwc-says.html",
        "source": "computerworld.com",
        "published": "2026-06-24T04:05:00+00:00",
        "summary": "PwC's signal is that the bottom rung of the AI labor market is getting pulled upward. Entry-level workers are being asked to show judgment, adaptability, and senior-style leverage before the old apprenticeship path has time to form.",
        "imageUrl": "https://www.computerworld.com/wp-content/uploads/2026/06/4188067-0-04562000-1782298982-future-ready-IT-workforce-shutterstock_2677450619.jpg?quality=50&strip=all&w=1024",
        "stages": [
          "Unhook Identity",
          "Reclaim Value"
        ],
        "keyPoints": [
          "Generative AI is raising skill expectations even for workers at the start of their careers.",
          "The old promise of learning slowly inside a junior role is being compressed by AI-assisted work.",
          "For TGR, the useful move is separating human value from the entry-level label itself."
        ]
      },
      {
        "title": "Agentic AI reshapes jobs, skills and HR models as governments rethink the future of work",
        "url": "https://www.khaleejtimes.com/business/agentic-ai-reshapes-jobs-skills-and-hr-models-as-governments-rethink-the-future-of-work",
        "source": "khaleejtimes.com",
        "published": "2026-06-23T05:47:00+00:00",
        "summary": "A Dubai forum puts agentic AI inside the operating model of work, not outside it as a novelty. The story matters because governments and HR leaders are now treating skills, roles, and human judgment as active design problems.",
        "imageUrl": "https://imgengine.khaleejtimes.com/khaleejtimes-english/2026-06-23/v1mmkcze/Agentic-AI-forum.jpeg?width=1200&height=630&q=60&format=auto&ogImage=true&mode=crop&rect=0,0,7008,4672",
        "stages": [
          "Discover AI's Power",
          "Unhook Identity"
        ],
        "keyPoints": [
          "AI agents are being discussed as forces that reshape workforce structures, skills demand, and leadership models.",
          "The article keeps human judgment central even as more work becomes agent-assisted.",
          "The TGR signal is that institutions are starting to redesign work around AI rather than merely add tools to existing jobs."
        ]
      },
      {
        "title": "Microsoft's AI Education Lead Says Job Fear Is Real. Here's The Fix",
        "url": "https://www.forbes.com/sites/danfitzpatrick/2026/06/22/microsofts-ai-education-lead-says-job-fear-is-real-heres-the-fix/",
        "source": "forbes.com",
        "published": "2026-06-22T03:58:00+00:00",
        "summary": "Microsoft's education AI lead names the fear students already feel: the labor market is changing faster than credentials can explain. The deeper signal is that purpose and adaptable judgment are becoming career infrastructure, not soft extras.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a3908e60d0b184acc61cf8a/0x0.jpg?format=jpg&crop=4048,2275,x0,y0,safe&height=900&width=1600&fit=bounds",
        "stages": [
          "Find Your Purpose",
          "Unhook Identity"
        ],
        "keyPoints": [
          "Justin Spelhaug runs Microsoft's $4B education AI effort.",
          "He says student fear of AI taking jobs is rational, and the skill that beats it is not purely technical.",
          "For TGR, the human task is to build direction before the market assigns identity by role."
        ]
      },
      {
        "title": "Oracle layoffs: Tech giant cuts 21,000 jobs as AI investments reshape workforce- Moneycontrol.com",
        "url": "https://www.moneycontrol.com/technology/oracle-layoffs-tech-giant-cuts-21-000-jobs-as-ai-investments-reshape-workforce-article-13956730.html",
        "source": "moneycontrol.com",
        "published": "2026-06-23T02:58:00+00:00",
        "summary": "Oracle's reported 21,000 job cuts make the AI workforce shift concrete. The hard lesson is that people need value they can carry across roles when companies redesign the roles themselves.",
        "imageUrl": "https://images.moneycontrol.com/static-mcnews/2026/04/20260401082814_MixCollage-01-Apr-2026-01-53-PM-7018.jpg",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "Oracle has cut around 21,000 jobs globally over the past year while realigning around AI.",
          "The story turns AI workforce restructuring from abstraction into operating policy.",
          "The TGR question is what human value survives when the company rewrites the org chart."
        ]
      },
      {
        "title": "PwC chairman pushes back on fears of AI-driven mass layoffs, says AI is adding more jobs",
        "url": "https://indianexpress.com/article/technology/artificial-intelligence/pwc-chairman-pushes-back-on-fears-of-ai-driven-mass-layoffs-says-ai-is-adding-more-jobs-10753088/",
        "source": "indianexpress.com",
        "published": "2026-06-23T07:19:18+00:00",
        "summary": "PwC's chair offers the counterweight to the layoff story: effective AI adoption may expand work instead of simply removing it. The tension is the point, because workers still have to repurpose themselves while leaders argue over the net effect.",
        "imageUrl": "https://images.indianexpress.com/2026/06/PwC-chairman-quells-fears-of-AI-driven-mass-layoffs-says-AI-adoption-is-adding-more-jobs.png",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "PwC's global chairman says organizations using AI well are focused on transformation and productivity gains, not only headcount cuts.",
          "The claim complicates the simple story that AI equals mass layoffs.",
          "For TGR, the practical signal is still the same: identity cannot depend on a single employer's version of the future."
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-23-microsoft-job-fear-meets-oracle-cuts": {
    "slug": "2026-06-23-microsoft-job-fear-meets-oracle-cuts",
    "date": "2026-06-23",
    "title": "Microsoft Job Fear Meets Oracle Cuts",
    "pattern": "Today's stories split the AI transition between fear and agency: students worry about jobs, Oracle cuts roles, and AI begins shaping even how young people discover universities. At the same time, Picsart's creator economy story shows value moving toward people who can claim audience, voice, and leverage. Purpose formation now has to happen earlier and more deliberately than the old career path required.",
    "stages": [
      "Unhook Identity",
      "Find Your Purpose",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://images.moneycontrol.com/static-mcnews/2026/04/20260401082814_MixCollage-01-Apr-2026-01-53-PM-7018.jpg",
    "stories": [
      {
        "title": "Microsoft's AI Education Lead Says Job Fear Is Real. Here's The Fix",
        "url": "https://www.forbes.com/sites/danfitzpatrick/2026/06/22/microsofts-ai-education-lead-says-job-fear-is-real-heres-the-fix/",
        "source": "forbes.com",
        "published": "2026-06-22T03:58:00+00:00",
        "summary": "Microsoft's education AI lead is naming the anxiety students already feel: the labor market is changing faster than credentials can explain. The signal is that purpose and adaptable human judgment are becoming career infrastructure, not soft extras.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a3908e60d0b184acc61cf8a/0x0.jpg?format=jpg&crop=4048,2275,x0,y0,safe&height=900&width=1600&fit=bounds",
        "stages": [
          "Find Your Purpose",
          "Unhook Identity"
        ],
        "keyPoints": [
          "Justin Spelhaug runs Microsoft's $4B education AI effort.",
          "He says student fear of AI taking jobs is rational, and the skill that beats it is not purely technical.",
          "For TGR, the useful move is separating identity from the first job title the market offers."
        ]
      },
      {
        "title": "Oracle layoffs: Tech giant cuts 21,000 jobs as AI investments reshape workforce- Moneycontrol.com",
        "url": "https://www.moneycontrol.com/technology/oracle-layoffs-tech-giant-cuts-21-000-jobs-as-ai-investments-reshape-workforce-article-13956730.html",
        "source": "moneycontrol.com",
        "published": "2026-06-23T02:58:00+00:00",
        "summary": "Oracle's reported 21,000 job cuts turn the AI workforce shift from abstraction into operating policy. The hard lesson is that people need value they can carry across roles when companies redesign the roles themselves.",
        "imageUrl": "https://images.moneycontrol.com/static-mcnews/2026/04/20260401082814_MixCollage-01-Apr-2026-01-53-PM-7018.jpg",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "Oracle has cut around 21,000 jobs globally over the past year while realigning around AI.",
          "The layoff story makes the work-identity split immediate, not theoretical.",
          "The TGR question is what human value survives when the company rewrites the org chart."
        ]
      },
      {
        "title": "Oracle cuts 21,000 jobs globally as AI reshapes its workforce",
        "url": "https://nairametrics.com/2026/06/23/oracle-cuts-21000-jobs-globally-as-ai-reshapes-its-workforce/",
        "source": "nairametrics.com",
        "published": "2026-06-23T08:00:37+00:00",
        "summary": "A second report reinforces the same Oracle pattern: AI investment is arriving with structural workforce reduction. When a signal repeats across sources, it points less to a single company's cuts and more to a broader repurposing of labor.",
        "imageUrl": "https://nairametrics.com/wp-content/uploads/2025/09/Larry-ellison.webp",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "Nairametrics also reports roughly 21,000 Oracle roles cut globally in the past year.",
          "The story frames the reductions as part of restructuring around artificial intelligence.",
          "Repeated reporting strengthens the day's core signal: identity cannot be outsourced to employer stability."
        ]
      },
      {
        "title": "AI Is Rewriting How Students Discover Universities",
        "url": "https://www.forbes.com/councils/forbescommunicationscouncil/2026/06/23/ai-is-rewriting-how-students-discover-universities/",
        "source": "forbes.com",
        "published": "2026-06-23T04:00:00+00:00",
        "summary": "University discovery is moving into AI-shaped environments where institutions have less control over what students see. That changes how young people form direction, compare options, and start creating a path before the old gatekeepers can fully explain it.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/690b77abd9e6e29d8223ff9a/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Find Your Purpose",
          "Start Creating"
        ],
        "keyPoints": [
          "Students are still researching schools, but more of that search now happens in AI-mediated spaces.",
          "Institutions have less visibility and control over how they are discovered and compared.",
          "The signal points to purpose formation happening inside new discovery systems."
        ]
      },
      {
        "title": "Where creativity pays: Inside Picsart's creator community | TechCrunch",
        "url": "https://techcrunch.com/sponsor/picsart-2/where-creativity-pays-inside-picsarts-creator-community/",
        "source": "techcrunch.com",
        "published": "2026-06-22T10:01:00+00:00",
        "summary": "Picsart's creator-community story puts money and leverage back at the center of creativity. In a world where execution keeps getting automated, the durable work is learning how creators capture value instead of only feeding platforms.",
        "imageUrl": "https://techcrunch.com/wp-content/uploads/2026/06/PicsArt-TechCrunch-2039938-Custom-Sponsored-Article-1200x1200-1.jpg?w=1200",
        "stages": [
          "Reclaim Value",
          "Discover AI's Power"
        ],
        "keyPoints": [
          "The creator economy is described as a $252 billion industry, but many creators still do not share meaningfully in the upside.",
          "The old bargain asks creators to grow an audience first and maybe get paid later.",
          "TGR relevance: creative value has to be claimed, not merely produced."
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-22-ai-moves-into-the-workday": {
    "date": "2026-06-22",
    "slug": "2026-06-22-ai-moves-into-the-workday",
    "title": "Job Fear Meets AI Education",
    "pattern": "The day's pattern is work identity moving into systems design. AI agents are getting identities and access, leaders are comparing AI to an industrial revolution, and education voices are telling students their fear is rational. The human answer is not panic or blind optimism; it is building AI fluency around human-centered judgment before institutions redesign the roles.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Find Your Purpose",
      "Discover AI's Power"
    ],
    "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a3908e60d0b184acc61cf8a/0x0.jpg?format=jpg&crop=4048,2275,x0,y0,safe&height=900&width=1600&fit=bounds",
    "stories": [
      {
        "title": "Microsoft's AI Education Lead Says Job Fear Is Real. Here's The Fix",
        "source": "forbes.com",
        "url": "https://www.forbes.com/sites/danfitzpatrick/2026/06/22/microsofts-ai-education-lead-says-job-fear-is-real-heres-the-fix/",
        "published": "2026-06-22T03:58:00+00:00",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a3908e60d0b184acc61cf8a/0x0.jpg?format=jpg&crop=4048,2275,x0,y0,safe&height=900&width=1600&fit=bounds",
        "summary": "This matters because people need a clearer inner compass before the labor market tells them who they are allowed to be.",
        "keyPoints": [
          "Justin Spelhaug runs Microsoft's $4B education AI effort.",
          "He says students' fear of AI taking their jobs is rational and the skill that beats it isn't technical.",
          "Source signal: forbes.com is connecting this story to ai agents workplace jobs."
        ],
        "stages": [
          "Find Your Purpose",
          "Unhook Identity"
        ]
      },
      {
        "title": "AI Layoffs Are Here, But They Don’t Mean What You Think",
        "source": "forbes.com",
        "url": "https://www.forbes.com/sites/bernardmarr/2026/06/22/ai-layoffs-are-here-but-they-dont-mean-what-you-think/",
        "published": "2026-06-21T22:33:00+00:00",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a38c8bbc4ed237ab060e054/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "As companies pour billions into AI infrastructure, cloud computing and specialist skills, the latest job cuts reveal how businesses are reshaping themselves around AI.",
          "Source signal: forbes.com is connecting this story to ai layoffs job cuts workforce.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity",
          "Reclaim Value"
        ]
      },
      {
        "title": "NewCore Raises $66M To Give AI Agents Work Identities In 2026 - Memeburn",
        "source": "memeburn.com",
        "url": "https://memeburn.com/newcore-raises-66m-to-give-ai-agents-work-identities-in-2026/",
        "published": "2026-06-20T03:54:07+00:00",
        "imageUrl": "https://memeburn.com/wp-content/uploads/2026/06/NewCore-Raises-66M-To-Give-AI-Agents-Work-Identities-In-2026-1024x576.png",
        "summary": "This matters because the capability curve is moving from novelty into operating reality.",
        "keyPoints": [
          "NewCore raised $66M to manage AI agent identities as companies rethink security, access and automation in South Africa.",
          "Source signal: memeburn.com is connecting this story to ai agents workplace jobs.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Discover AI's Power"
        ]
      },
      {
        "title": "Jensen Huang says AI will reshape work like the Industrial Revolution and the US 'should absolutely lead'",
        "source": "foxnews.com",
        "url": "https://www.foxnews.com/media/jensen-huang-says-ai-reshape-work-like-industrial-revolution-us-should-absolutely-lead",
        "published": "2026-06-20T06:07:00+00:00",
        "imageUrl": "https://static.foxnews.com/foxnews.com/content/uploads/2024/03/Nvidia-CEO-Jensen-Huang-Blackwell-GTC-2024.gif",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "Nvidia CEO Jensen Huang says AI will transform the workforce like the Industrial Revolution, creating new jobs while reshaping how Americans work.",
          "Source signal: foxnews.com is connecting this story to artificial intelligence productivity jobs.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity"
        ]
      },
      {
        "title": "Human-centered AI could be PH’s competitive edge",
        "source": "sunstar.com.ph",
        "url": "https://www.sunstar.com.ph/cebu/human-centered-ai-could-be-phs-competitive-edge",
        "published": "2026-06-22T04:13:00+00:00",
        "imageUrl": "https://cf-images.assettype.com/sunstar%2F2024-05%2F4177634e-2b4a-43ae-ae2d-5a16eac4e5d8%2FArtificial_Intelligence.jpg?rect=0%2C53%2C750%2C394&w=1200&ar=40%3A21&auto=format%2Ccompress&ogImage=true&mode=crop&enlarge=true&overlay=false&overlay_position=bottom&overlay_width=100",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "AS ARTIFICIAL intelligence reshapes industries worldwide, Philippine companies should focus on using the technology to enhance workers rather than replace them,",
          "Source signal: sunstar.com.ph is connecting this story to ai skills reskilling workers.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity"
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-21-ai-moves-into-the-workday": {
    "date": "2026-06-21",
    "slug": "2026-06-21-ai-moves-into-the-workday",
    "title": "AI Agents Get Work Identities",
    "pattern": "AI is becoming a coworker with credentials, permissions, and practical reach, while companies keep using AI language to explain job cuts. That makes the old question 'will AI replace me?' too narrow. The better question is what human voice, accountability, and creative judgment become more valuable when agents can take on more of the work.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://memeburn.com/wp-content/uploads/2026/06/NewCore-Raises-66M-To-Give-AI-Agents-Work-Identities-In-2026-1024x576.png",
    "stories": [
      {
        "title": "AI agents need more than reasoning: they need to actually use the web",
        "source": "digitaltrends.com",
        "url": "https://www.digitaltrends.com/contributor-content/ai-agents-need-more-than-reasoning-they-need-to-actually-use-the-web/",
        "published": "2026-06-19T11:49:46+00:00",
        "imageUrl": "https://www.digitaltrends.com/tachyon/2026/06/AdobeStock_567681994.jpg?resize=1200%2C630",
        "summary": "This matters because the capability curve is moving from novelty into operating reality.",
        "keyPoints": [
          "A company rolls out an AI customer service assistant.",
          "The model behind it is current and capable enough for the job.",
          "Source signal: digitaltrends.com is connecting this story to ai agents workplace jobs."
        ],
        "stages": [
          "Discover AI's Power",
          "Unhook Identity"
        ]
      },
      {
        "title": "NewCore Raises $66M To Give AI Agents Work Identities In 2026 - Memeburn",
        "source": "memeburn.com",
        "url": "https://memeburn.com/newcore-raises-66m-to-give-ai-agents-work-identities-in-2026/",
        "published": "2026-06-20T03:54:07+00:00",
        "imageUrl": "https://memeburn.com/wp-content/uploads/2026/06/NewCore-Raises-66M-To-Give-AI-Agents-Work-Identities-In-2026-1024x576.png",
        "summary": "This matters because the capability curve is moving from novelty into operating reality.",
        "keyPoints": [
          "NewCore raised $66M to manage AI agent identities as companies rethink security, access and automation in South Africa.",
          "Source signal: memeburn.com is connecting this story to ai agents workplace jobs.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Discover AI's Power"
        ]
      },
      {
        "title": "Adobe’s AI Edge: Turning Solo Creators Into Global Media Brands",
        "source": "forbes.com",
        "url": "https://www.forbes.com/sites/jamiegutfreund/2026/06/16/adobes-ai-edge-turning-solo-creators-into-global-media-brands/",
        "published": "2026-06-16T06:41:00+00:00",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a30d0afa8d3ddcf046cccc3/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "summary": "This matters because it points to the human value that remains when execution gets automated.",
        "keyPoints": [
          "As Cannes Lions begins next week, Adobe research shows 87% of creators say AI is accelerating growth while making creativity and judgment more valuable",
          "Source signal: forbes.com is connecting this story to ai creativity work creators.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ]
      },
      {
        "title": "The AI jobs crisis no one is talking about (Opinion)",
        "source": "dailycamera.com",
        "url": "https://www.dailycamera.com/2026/06/20/ai-artificial-intelligence-job-crisis-chatgpt-work-employment-opinion/",
        "published": "2026-06-20T11:00:03+00:00",
        "imageUrl": "https://www.dailycamera.com/wp-content/uploads/2026/05/AI_Health_Care_Poll_84564_1d4d7c.jpg?w=1024&h=682",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "Source signal: dailycamera.com is connecting this story to artificial intelligence productivity jobs.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity"
        ]
      },
      {
        "title": "Is AI replacing tech workers or providing an excuse for job cuts?",
        "source": "inquirer.com",
        "url": "https://www.inquirer.com/business/ai-tech-workers-layoffs-companies-meta-coinbase-block-snap-intuit-cisco-cloudflare-20260614.html",
        "published": "2026-06-14T09:01:00+00:00",
        "imageUrl": "https://www.inquirer.com/resizer/v2/DAGFY4WR6RSHQPBRIV4JINOW6E.jpg?auth=d60528a00ead4069abe3aa99c54f35f9604c9f6bb4f4b04bf05d007e1dce5145&width=760&height=507&smart=true",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "Tech industry layoffs are accelerating, and executives have been quick to say it’s because their companies are doing more with artificial intelligence, even when there may be more to it.",
          "Source signal: inquirer.com is connecting this story to ai layoffs job cuts workforce.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity"
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-20-agents-enter-the-real-economy": {
    "date": "2026-06-20",
    "slug": "2026-06-20-agents-enter-the-real-economy",
    "title": "Agents Enter The Real Economy",
    "pattern": "AI is moving from answer machine to active participant. That makes the old productivity frame too small. The question becomes who directs the work, what judgment remains human, and where people learn to create with systems instead of merely using tools.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://www.digitaltrends.com/tachyon/2026/06/AdobeStock_567681994.jpg?resize=1200%2C630",
    "stories": [
      {
        "title": "AI agents need more than reasoning: they need to actually use the web",
        "source": "digitaltrends.com",
        "url": "https://www.digitaltrends.com/contributor-content/ai-agents-need-more-than-reasoning-they-need-to-actually-use-the-web/",
        "published": "2026-06-19T11:49:46+00:00",
        "imageUrl": "https://www.digitaltrends.com/tachyon/2026/06/AdobeStock_567681994.jpg?resize=1200%2C630",
        "summary": "This matters because the capability curve is moving from novelty into operating reality.",
        "keyPoints": [
          "A company rolls out an AI customer service assistant.",
          "The model behind it is current and capable enough for the job.",
          "Source signal: digitaltrends.com is connecting this story to ai agents workplace jobs."
        ],
        "stages": [
          "Discover AI's Power",
          "Unhook Identity"
        ]
      },
      {
        "title": "Ray Dalio Warns AI Will Reshape The Economy: 'It's Also Going To Bring Jobs Down A Lot'",
        "source": "finance.yahoo.com",
        "url": "https://finance.yahoo.com/technology/ai/articles/ray-dalio-warns-ai-reshape-203113909.html",
        "published": "2026-06-18T15:46:00+00:00",
        "imageUrl": "",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "On Tuesday, billionaire investor Ray Dalio warned that artificial intelligence could significantly reshape the global economy by boosting productivity while reducing jobs.",
          "AI Productivity Boom Raises Job Loss Concerns In a post on X, the billionaire investor said AI represents...",
          "Source signal: finance.yahoo.com is connecting this story to artificial intelligence productivity jobs."
        ],
        "stages": [
          "Unhook Identity"
        ]
      },
      {
        "title": "The AI jobs crisis no one is talking about (Opinion)",
        "source": "dailycamera.com",
        "url": "https://www.dailycamera.com/2026/06/20/ai-artificial-intelligence-job-crisis-chatgpt-work-employment-opinion/",
        "published": "2026-06-20T11:00:03+00:00",
        "imageUrl": "https://www.dailycamera.com/wp-content/uploads/2026/05/AI_Health_Care_Poll_84564_1d4d7c.jpg?w=1024&h=682",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "Source signal: dailycamera.com is connecting this story to ai agents workplace jobs.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity"
        ]
      },
      {
        "title": "Adobe’s AI Edge: Turning Solo Creators Into Global Media Brands",
        "source": "forbes.com",
        "url": "https://www.forbes.com/sites/jamiegutfreund/2026/06/16/adobes-ai-edge-turning-solo-creators-into-global-media-brands/",
        "published": "2026-06-16T06:41:00+00:00",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a30d0afa8d3ddcf046cccc3/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "summary": "This matters because it points to the human value that remains when execution gets automated.",
        "keyPoints": [
          "As Cannes Lions begins next week, Adobe research shows 87% of creators say AI is accelerating growth while making creativity and judgment more valuable",
          "Source signal: forbes.com is connecting this story to ai creativity work creators.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ]
      },
      {
        "title": "A Founder Ran the Numbers on AI-Generated Creative Content. The Results Were a Reality Check",
        "source": "inc.com",
        "url": "https://www.inc.com/netta-jenkins/ai-can-generate-content-it-still-struggles-to-replicate-human-creativity/91360916",
        "published": "2026-06-19T07:09:00+00:00",
        "imageUrl": "",
        "summary": "The Inc. story is a useful reality check on AI creativity: cheap output is not the same as effective creative work. If AI-generated ads underperform human-made ones, the value shifts back toward taste, audience understanding, and the judgment to know what should be made in the first place.",
        "keyPoints": [
          "A founder's performance data showed AI-generated creative did not automatically beat human-made ads.",
          "The story separates production speed from creative effectiveness, which matters as brands chase lower-cost content.",
          "For TGR, the signal is that human taste and judgment still create value when AI makes output abundant."
        ],
        "stages": [
          "Start Creating",
          "Reclaim Value"
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-19-ai-moves-into-the-workday": {
    "date": "2026-06-19",
    "slug": "2026-06-19-ai-moves-into-the-workday",
    "title": "AI Education Meets The Work Shift",
    "pattern": "Education and work are both being forced to move from compliance to capability. AI is turning cheating, coding, creative production, and email delegation into tests of whether people understand the systems they use, not just whether they can produce output. AI literacy is becoming protective value: people who can direct the tool thoughtfully are less exposed than people who only perform the old task.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Find Your Purpose",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://s.hdnux.com/photos/01/66/47/07/31093195/3/rawImage.jpg",
    "stories": [
      {
        "title": "AI cheating crisis may be a gift, education experts say",
        "source": "timesunion.com",
        "url": "https://www.timesunion.com/education/article/educators-predict-bright-future-artificial-22302946.php",
        "published": "2026-06-19T10:00:00+00:00",
        "imageUrl": "https://s.hdnux.com/photos/01/66/47/07/31093195/3/rawImage.jpg",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "Some experts think AI will usher in a vastly better world in which students learn deeply and workers spend more time on parts of their job they love.",
          "Source signal: timesunion.com is connecting this story to ai education careers graduates.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity",
          "Find Your Purpose"
        ]
      },
      {
        "title": "Adobe’s AI Edge: Turning Solo Creators Into Global Media Brands",
        "source": "forbes.com",
        "url": "https://www.forbes.com/sites/jamiegutfreund/2026/06/16/adobes-ai-edge-turning-solo-creators-into-global-media-brands/",
        "published": "2026-06-16T06:41:00+00:00",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a30d0afa8d3ddcf046cccc3/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "summary": "This matters because it points to the human value that remains when execution gets automated.",
        "keyPoints": [
          "As Cannes Lions begins next week, Adobe research shows 87% of creators say AI is accelerating growth while making creativity and judgment more valuable",
          "Source signal: forbes.com is connecting this story to ai creativity work creators.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ]
      },
      {
        "title": "Companies are using AI agents to cover for staff on vacation — but can they really help you dig out from a mountain of email, and can you trust them? - AOL",
        "source": "aol.com",
        "url": "https://www.aol.com/finance/companies-using-ai-agents-cover-175500529.html",
        "published": "2026-06-17T17:55:00+00:00",
        "imageUrl": "",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "Since the AI boom began, employees across industries have been wondering what the technology could mean for their jobs.",
          "Source signal: aol.com is connecting this story to ai agents workplace jobs.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity",
          "Discover AI's Power"
        ]
      },
      {
        "title": "Momentum Builds to Expand Coding Education to Learning About AI 'Under the Hood'",
        "source": "edweek.org",
        "url": "https://www.edweek.org/technology/momentum-builds-to-expand-coding-education-to-learning-about-ai-under-the-hood/2026/06",
        "published": "2026-06-18T01:41:31.691000+00:00",
        "imageUrl": "",
        "summary": "This matters because people need a clearer inner compass before the labor market tells them who they are allowed to be.",
        "keyPoints": [
          "CodeAI CEO talks about artificial intelligence and the future of computer science education.",
          "Source signal: edweek.org is connecting this story to ai education careers graduates.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Find Your Purpose",
          "Start Creating"
        ]
      },
      {
        "title": "As job cuts rise, AI users appear better protected: Report- Moneycontrol.com",
        "source": "moneycontrol.com",
        "url": "https://www.moneycontrol.com/world/as-job-cuts-rise-ai-users-appear-better-protected-report-article-13953462.html",
        "published": "2026-06-18T10:19:00+00:00",
        "imageUrl": "https://images.moneycontrol.com/static-mcnews/2026/06/20260609103801_AI-Jobs.jpg",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them.",
        "keyPoints": [
          "Source signal: moneycontrol.com is connecting this story to ai layoffs job cuts workforce.",
          "TGR relevance: the story helps show where AI is changing work, value, agency, or creation."
        ],
        "stages": [
          "Unhook Identity"
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-18-ai-moves-into-the-workday": {
    "date": "2026-06-18",
    "title": "AI Literacy Becomes The Baseline",
    "slug": "2026-06-18-ai-moves-into-the-workday",
    "pattern": "AI literacy is crossing from advantage to baseline. Government hiring, graduate roles, creator work, and layoff narratives all point to the same shift: execution is easier, but trusted judgment, voice, and direction are harder to replace. Treat AI fluency as table stakes and human point of view as the real differentiator.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Find Your Purpose",
      "Start Creating"
    ],
    "imageUrl": "https://cdn.govexec.com/media/img/cd/2026/06/17/NGA_AOP_image_1-1/open-graph.png",
    "stories": [
      {
        "title": "AI skills are becoming part of the hiring baseline at the National Geospatial-Intelligence Agency",
        "url": "https://www.govexec.com/technology/2026/06/ai-skills-hiring-baseline-national-geospatial-intelligence-agency/414251/",
        "source": "govexec.com",
        "published": "2026-06-18T11:00:00+00:00",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them. AI literacy is becoming part of the baseline expectation for knowledge work, which means people need to name the human value that travels with them as the role keeps changing.",
        "imageUrl": "https://cdn.govexec.com/media/img/cd/2026/06/17/NGA_AOP_image_1-1/open-graph.png",
        "stages": [
          "Unhook Identity",
          "Reclaim Value"
        ],
        "keyPoints": [
          "The intelligence agency is reshaping training for both new and existing employees as it builds AI and data management into core job expectations across the workforce.",
          "AI fluency is moving from specialist skill to everyday job requirement.",
          "The TGR signal is that workers need a durable sense of value beyond any single job description."
        ]
      },
      {
        "title": "Adobe’s AI Edge: Turning Solo Creators Into Global Media Brands",
        "url": "https://www.forbes.com/sites/jamiegutfreund/2026/06/16/adobes-ai-edge-turning-solo-creators-into-global-media-brands/",
        "source": "forbes.com",
        "published": "2026-06-16T06:41:00+00:00",
        "summary": "This matters because it points to the human value that remains when execution gets automated. AI may multiply output, but the creator's taste, judgment, point of view, and relationship with an audience become the real scarce assets.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a30d0afa8d3ddcf046cccc3/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ],
        "keyPoints": [
          "Adobe research says 87% of creators report AI is accelerating growth while making creativity and judgment more valuable.",
          "Solo creators can now operate with leverage once reserved for larger media teams.",
          "The TGR signal is that human voice and direction matter more as production gets easier."
        ]
      },
      {
        "title": "AI is redefining entry-level roles – and young workers have the edge",
        "url": "https://www.hcamag.com/us/news/general/ai-is-redefining-entry-level-roles-and-young-workers-have-the-edge/579191",
        "source": "hcamag.com",
        "published": "2026-06-16T22:50:03+00:00",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them. Entry-level work is being renegotiated first, so young workers need more than tool familiarity; they need a clearer sense of purpose and value as the first rung changes shape.",
        "imageUrl": "https://cdn-res.keymedia.com/cms/images/us/037/0391_639172613132434169.png",
        "stages": [
          "Unhook Identity",
          "Find Your Purpose"
        ],
        "keyPoints": [
          "Recruitment experts say AI literacy is now a baseline expectation for graduates entering the workforce.",
          "The early-career bargain is changing as AI absorbs parts of the work people used to learn on.",
          "The TGR signal is that the first job matters less as an identity anchor and more as a launchpad for direction."
        ]
      },
      {
        "title": "Tech Layoffs Hit 1,115 a Day in 2026: Companies Cite AI but Cuts Fail to Boost Returns",
        "url": "https://www.techtimes.com/articles/318466/20260616/tech-layoffs-hit-1115-day-2026-companies-cite-ai-cuts-fail-boost-returns.htm",
        "source": "techtimes.com",
        "published": "2026-06-16T13:20:34+00:00",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them. Companies are citing AI as a reason to cut roles, but the deeper story is that identity and security cannot be outsourced to an employer's latest operating model.",
        "imageUrl": "https://d.techtimes.com/en/full/466792/hiring-expo.jpg",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "Tech layoffs in 2026 are averaging 1,115 job cuts per day as companies cite artificial intelligence to justify eliminating roles.",
          "A Gartner study cited in the story found companies cutting the most showed no improvement in financial returns.",
          "The TGR signal is that AI is becoming a management narrative as much as a technology story."
        ]
      },
      {
        "title": "AI Made Content Abundant. For Creators, Voice Is Now The Scarce Asset",
        "url": "https://www.forbes.com/sites/maureenkerr/2026/06/16/ai-made-content-abundant-for-creators-voice-is-now-the-scarce-asset/",
        "source": "forbes.com",
        "published": "2026-06-16T11:30:00+00:00",
        "summary": "This matters because it points to the human value that remains when execution gets automated. As AI floods the world with competent content, the differentiator becomes the perspective people trust and recognize as genuinely human.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a311e87a5a0ca492480343a/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ],
        "keyPoints": [
          "A 2026 survey of 16,000 creators shows voice and judgment, not volume, are now the scarce asset.",
          "AI makes publishing easier, but it also makes generic output less valuable.",
          "The TGR signal is that creators need to reclaim voice as durable human value and use AI to amplify it."
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-16-ai-moves-into-the-workday": {
    "date": "2026-06-16",
    "title": "AI Agents Need Human Control",
    "slug": "2026-06-16-ai-moves-into-the-workday",
    "pattern": "This issue is about control: agents are becoming capable enough to touch real systems, while companies are still using AI as a blunt story for cuts. The strongest human response is not to compete task-for-task, but to design clearer delegation, constraints, voice, and accountability. AI can multiply output; it cannot decide what deserves trust unless people stay in command.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Start Creating"
    ],
    "imageUrl": "https://www.computerworld.com/wp-content/uploads/2026/06/4185559-0-48713800-1781610470-youtube-thumbnail-uPpd9EJ4iNI_55eb26.jpg?quality=50&strip=all&w=1024",
    "stories": [
      {
        "title": "Why AI agents could create a new control and security crisis",
        "url": "https://www.computerworld.com/video/4185559/why-ai-agents-could-create-a-new-control-and-security-crisis.html",
        "source": "computerworld.com",
        "published": "2026-06-16T04:49:00+00:00",
        "summary": "This matters because the capability curve is moving from novelty into operating reality. As AI agents begin touching enterprise data, APIs, and workflows, the human question shifts from whether the tools work to who has judgment, authority, and accountability over what they do.",
        "imageUrl": "https://www.computerworld.com/wp-content/uploads/2026/06/4185559-0-48713800-1781610470-youtube-thumbnail-uPpd9EJ4iNI_55eb26.jpg?quality=50&strip=all&w=1024",
        "stages": [
          "Discover AI's Power",
          "Start Creating"
        ],
        "keyPoints": [
          "AI agents are rapidly evolving from productivity assistants into autonomous systems capable of accessing enterprise data, APIs, applications, and business processes.",
          "The control problem becomes more urgent as agents gain permission to act inside real systems.",
          "The TGR signal is that people need to create with AI while staying responsible for the systems they unleash."
        ]
      },
      {
        "title": "Adobe’s AI Edge: Turning Solo Creators Into Global Media Brands",
        "url": "https://www.forbes.com/sites/jamiegutfreund/2026/06/16/adobes-ai-edge-turning-solo-creators-into-global-media-brands/",
        "source": "forbes.com",
        "published": "2026-06-16T06:41:00+00:00",
        "summary": "This matters because it points to the human value that remains when execution gets automated. AI gives solo creators scale, but the work still depends on human taste, voice, direction, and judgment.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a30d0afa8d3ddcf046cccc3/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ],
        "keyPoints": [
          "Adobe research shows creators say AI is accelerating growth while making creativity and judgment more valuable.",
          "Production leverage is becoming available to individuals who once needed teams or large budgets.",
          "The TGR signal is that reclaimed human value becomes more powerful when paired with new creative instruments."
        ]
      },
      {
        "title": "Build AI agents that do one job",
        "url": "https://www.fastcompany.com/91558102/build-ai-agents-that-do-one-job",
        "source": "fastcompany.com",
        "published": "2026-06-15T07:23:00+00:00",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them. The clearer the agent's job becomes, the clearer the human's role must become too: setting context, constraints, standards, and purpose.",
        "imageUrl": "",
        "stages": [
          "Unhook Identity",
          "Discover AI's Power"
        ],
        "keyPoints": [
          "The article argues that every agent should have one clear job, with a defined input, output, and constraint.",
          "Vague agents create vague accountability; focused agents make delegation safer and more useful.",
          "The TGR signal is that humans need to stop identifying with every task and start designing the work intentionally."
        ]
      },
      {
        "title": "Tech Layoffs Hit 1,115 a Day in 2026: Companies Cite AI but Cuts Fail to Boost Returns",
        "url": "https://www.techtimes.com/articles/318466/20260616/tech-layoffs-hit-1115-day-2026-companies-cite-ai-cuts-fail-boost-returns.htm",
        "source": "techtimes.com",
        "published": "2026-06-16T13:20:34+00:00",
        "summary": "This matters to The Great Repurpose because it separates the human being from the job wrapper around them. AI is now part of the explanation companies use for layoffs, but the deeper human work is learning not to let that explanation define identity or worth.",
        "imageUrl": "https://d.techtimes.com/en/full/466792/hiring-expo.jpg",
        "stages": [
          "Unhook Identity"
        ],
        "keyPoints": [
          "Tech layoffs in 2026 are averaging 1,115 job cuts per day as companies cite AI in workforce reductions.",
          "The story notes that companies cutting the most did not necessarily see better financial returns.",
          "The TGR signal is that AI disruption is both a labor story and a meaning story."
        ]
      },
      {
        "title": "AI Made Content Abundant. For Creators, Voice Is Now The Scarce Asset",
        "url": "https://www.forbes.com/sites/maureenkerr/2026/06/16/ai-made-content-abundant-for-creators-voice-is-now-the-scarce-asset/",
        "source": "forbes.com",
        "published": "2026-06-16T11:30:00+00:00",
        "summary": "This matters because it points to the human value that remains when execution gets automated. When content becomes abundant, voice and judgment become the scarce assets people actually seek out.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a311e87a5a0ca492480343a/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ],
        "keyPoints": [
          "A 2026 survey of 16,000 creators shows voice and judgment, not volume, are now the scarce asset.",
          "AI abundance makes generic content less valuable and distinctive human perspective more valuable.",
          "The TGR signal is that creators need to reclaim what makes their work recognizably theirs."
        ]
      }
    ],
    "sourceStatus": "generated"
  },
  "2026-06-13-ai-lays-off-america-while-apple-launches-siri": {
    "date": "2026-06-13",
    "title": "AI Lays Off America While Apple Launches Siri",
    "slug": "2026-06-13-ai-lays-off-america-while-apple-launches-siri",
    "pattern": "AI is no longer the future of work — it's the present reason people are losing it. But the people who thrive will be those who treat AI as a collaborator, not a replacement. The Great Repurpose isn't a luxury anymore; it's a survival skill.",
    "stages": [
      "Unhook Identity",
      "Reclaim Value",
      "Discover AI's Power",
      "Find Your Purpose",
      "Start Creating"
    ],
    "imageUrl": "https://media.assettype.com/outlookbusiness/2026-04-24/zfplh735/5.png?w=1200&ar=40%3A21&auto=format%2Ccompress&ogImage=true&mode=crop&enlarge=true&overlay=false&overlay_position=bottom&overlay_width=100",
    "stories": [
      {
        "title": "AI Overtakes All Other Reasons For US Job Cuts As Layoffs Surge In 2026",
        "url": "https://www.outlookbusiness.com/corporate/ai-overtakes-all-other-reasons-for-us-job-cuts-as-layoffs-surge-in-2026",
        "source": "outlookbusiness.com",
        "published": "",
        "summary": "This is the labor-market alarm bell in plain language: AI is not just a tool companies are testing, it is becoming a reason companies give for cutting jobs. The emotional reality is that people are being forced to repurpose under pressure.",
        "imageUrl": "https://media.assettype.com/outlookbusiness/2026-04-24/zfplh735/5.png?w=1200&ar=40%3A21&auto=format%2Ccompress&ogImage=true&mode=crop&enlarge=true&overlay=false&overlay_position=bottom&overlay_width=100",
        "stages": [
          "Unhook Identity",
          "Reclaim Value"
        ],
        "keyPoints": [
          "AI is being named as a leading driver of job cuts in the headline data.",
          "The story moves AI displacement from future anxiety into present workforce planning.",
          "TGR relevance: people need identity and value work before disruption becomes personal."
        ]
      },
      {
        "title": "Apple Introduces Siri AI, a Profoundly More Capable and Personal Assistant",
        "url": "https://www.apple.com/newsroom/2026/06/apple-introduces-siri-ai-a-profoundly-more-capable-and-personal-assistant/",
        "source": "apple.com",
        "published": "",
        "summary": "A more capable Siri would put AI assistance deeper into the daily rhythm of ordinary users. The signal is mainstreaming: AI becomes less like a destination app and more like an always-available layer between intention and action.",
        "imageUrl": "https://www.apple.com/newsroom/images/2026/06/apple-introduces-siri-ai-a-profoundly-more-capable-and-personal-assistant/tile/Apple-Siri-AI-hero-260608-lp.jpg.og.jpg?202606121954",
        "stages": [
          "Discover AI's Power",
          "Reclaim Value"
        ],
        "keyPoints": [
          "Apple-style integration can make AI feel normal to people who never went looking for it.",
          "The assistant layer will shape how people search, decide, communicate, and create.",
          "This is Discover AI's Power with a human-agency question attached: who is steering the assistant?"
        ]
      },
      {
        "title": "AI, Jobs, and the Next Generation",
        "url": "https://blogs.microsoft.com/on-the-issues/2026/06/10/ai-jobs-and-the-next-generation/",
        "source": "blogs.microsoft.com",
        "published": "",
        "summary": "Microsoft framing AI and jobs for the next generation points to the education gap underneath the labor story. Young people do not just need tool familiarity. They need a way to build identity, judgment, and purpose in a market that keeps shifting.",
        "imageUrl": "https://blogs.microsoft.com/wp-content/uploads/sites/5/2026/06/BANNERS_BRAD_POSTA-1024x576.png",
        "stages": [
          "Find Your Purpose",
          "Unhook Identity"
        ],
        "keyPoints": [
          "The next generation is entering work at the same time AI is rewriting entry-level assumptions.",
          "Education has to prepare people for judgment and adaptability, not only technical fluency.",
          "TGR relevance: Find Your Purpose becomes a workforce skill, not a luxury."
        ]
      },
      {
        "title": "AI Isn't Replacing Creativity. It's Moving It Upstream.",
        "url": "https://www.forbes.com/sites/cathyrubin/2026/05/26/ai-isnt-replacing-creativity-its-moving-it-upstream/",
        "source": "forbes.com",
        "published": "",
        "summary": "The creative story gives the day its counterweight: even as AI pressures jobs, it can also move people toward higher-order creative judgment. The opportunity is real, but only for people willing to claim the directing role.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a11204aa488ec8b473b57df/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Start Creating",
          "Reclaim Value"
        ],
        "keyPoints": [
          "AI can make execution cheaper while increasing the value of taste and direction.",
          "Creatives need to move upstream into intent, framing, and quality judgment.",
          "This is Start Creating from a reclaimed sense of value."
        ]
      },
      {
        "title": "JPMorgan Chase Reclassifies AI as Core Infrastructure in $19.8B Tech Budget",
        "url": "https://www.businessinsider.com/jpmorgan-tech-budget-ai-20-billion-jamie-dimon-2026-2",
        "source": "businessinsider.com",
        "published": "",
        "summary": "When a major bank treats AI as core infrastructure, the workplace shift becomes structural. AI is no longer an innovation budget experiment. It is part of how the institution expects work to happen.",
        "imageUrl": "https://i.insider.com/699ce38d156648bc16a8c346?width=800&format=jpeg",
        "stages": [
          "Discover AI's Power",
          "Unhook Identity"
        ],
        "keyPoints": [
          "AI is being funded as foundational business infrastructure, not a side project.",
          "Large institutions are preparing for operating-model change at serious scale.",
          "TGR relevance: Discover AI's Power now means understanding the systems that will define future work."
        ]
      }
    ],
    "sourceStatus": "sent_html"
  },
  "2026-06-07-ai-reshapes-work-identity-and-creativity": {
    "date": "2026-06-07",
    "title": "AI Reshapes Work, Identity, And Creativity",
    "slug": "2026-06-07-ai-reshapes-work-identity-and-creativity",
    "pattern": "The signal is that AI is no longer only changing what people do. It is changing how people understand themselves, how companies explain job cuts, and where creative value lives. The human move is to name the part of us that remains durable before the market names us obsolete.",
    "stages": [
      "Reclaim Value",
      "Unhook Identity",
      "Find Your Purpose",
      "Start Creating"
    ],
    "imageUrl": "https://gcp-na-images.contentstack.com/v3/assets/bltea6093859af6183b/blt7f9b16d39bc44ab3/6a22353270c5a9918127c424/AI-Changing-Human.jpg?branch=production&width=1200&quality=75&auto=webp&crop=1200:675&height=675",
    "stories": [
      {
        "title": "AI Is Already Shaping Who We Are",
        "url": "https://time.com/article/2026/06/05/ai-is-already-shaping-who-we-are/",
        "source": "time.com",
        "published": "",
        "summary": "This is the identity layer of the AI transition: tools do not simply help us complete tasks, they start to shape how we think, choose, and relate. The Great Repurpose begins by noticing that change instead of sleepwalking through it.",
        "imageUrl": "https://gcp-na-images.contentstack.com/v3/assets/bltea6093859af6183b/blt7f9b16d39bc44ab3/6a22353270c5a9918127c424/AI-Changing-Human.jpg?branch=production&width=1200&quality=75&auto=webp&crop=1200:675&height=675",
        "stages": [
          "Unhook Identity",
          "Find Your Purpose"
        ],
        "keyPoints": [
          "AI influence is becoming personal and cultural, not only professional.",
          "The tools may shape habits, self-understanding, and expectations over time.",
          "This is Unhook Identity: stay awake to who you are becoming while the tools get more intimate."
        ]
      },
      {
        "title": "AI Overtakes All Other Reasons For US Job Cuts As Layoffs Surge In 2026",
        "url": "https://www.outlookbusiness.com/corporate/ai-overtakes-all-other-reasons-for-us-job-cuts-as-layoffs-surge-in-2026",
        "source": "outlookbusiness.com",
        "published": "",
        "summary": "The layoff signal is blunt: AI is becoming a named cause of job loss, not just an abstract future risk. That makes identity work urgent, because many people will be asked to redefine themselves faster than they expected.",
        "imageUrl": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/971609117608a5b0102a9373e92032e6.jpg",
        "stages": [
          "Unhook Identity",
          "Reclaim Value"
        ],
        "keyPoints": [
          "AI is being cited directly in workforce reductions.",
          "The disruption is moving from forecast to lived experience for workers.",
          "TGR relevance: people need to unhook their worth from roles that companies may rapidly redesign."
        ]
      },
      {
        "title": "AI Cited As Top Reason For US Job Cuts For Third Straight Month",
        "url": "https://www.cfodive.com/news/ai-cited-top-reason-us-job-cuts-third-straight-month/822029/",
        "source": "cfodive.com",
        "published": "",
        "summary": "A repeated monthly pattern changes the story from anomaly to trend. AI-related job cuts are becoming part of the operating logic of companies, which means workers need a repeatable way to respond.",
        "imageUrl": "https://media.deloitte.com/is/image/null:1200-x-627",
        "stages": [
          "Reclaim Value",
          "Unhook Identity"
        ],
        "keyPoints": [
          "Repeated AI-related job cut data suggests a sustained labor-market shift.",
          "The story reinforces that adaptation cannot be a one-time panic response.",
          "This is Reclaim Value: understand what part of your contribution survives the restructuring."
        ]
      },
      {
        "title": "AI Cultural Debt: The Hidden Cost of Speed-First Adoption",
        "url": "https://www.deloitte.com/us/en/insights/topics/talent/human-capital-trends/2026/ai-cultural-debt.html",
        "source": "deloitte.com",
        "published": "",
        "summary": "Cultural debt is what accumulates when companies adopt AI faster than people can make sense of it. The tool may work, but trust, clarity, and shared purpose can quietly break underneath it.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a11204aa488ec8b473b57df/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Find Your Purpose",
          "Reclaim Value"
        ],
        "keyPoints": [
          "Speed-first AI adoption can create hidden organizational costs.",
          "Culture, trust, and meaning need attention alongside efficiency and deployment.",
          "TGR relevance: Find Your Purpose is not soft. It is how groups stay coherent during acceleration."
        ]
      },
      {
        "title": "AI Isn’t Replacing Creativity. It’s Moving It Upstream.",
        "url": "https://www.forbes.com/sites/cathyrubin/2026/05/26/ai-isnt-replacing-creativity-its-moving-it-upstream/",
        "source": "forbes.com",
        "published": "",
        "summary": "Creativity is not disappearing. It is moving toward the choices that happen before execution: what to make, why it matters, how it should feel, and when it is good enough to share.",
        "imageUrl": "",
        "stages": [
          "Start Creating",
          "Reclaim Value"
        ],
        "keyPoints": [
          "AI shifts creative leverage toward framing, direction, and judgment.",
          "The person with taste and purpose becomes more valuable as execution gets cheaper.",
          "This is Start Creating after Reclaim Value: use the machine to express more of the human, not less."
        ]
      }
    ],
    "sourceStatus": "sent_html"
  },
  "2026-06-05-creative-control-in-the-age-of-ai": {
    "date": "2026-06-05",
    "title": "Creative Control In The Age Of AI",
    "slug": "2026-06-05-creative-control-in-the-age-of-ai",
    "pattern": "The old guard of creative ownership is fighting back. Adobe's Creator Act, the creator economy conversation, and the rise of AI agents all point to the same inflection point: human creators are demanding legal, technical, and economic guardrails over their work. The Great Repurpose is not just about adapting to AI. It is about asserting who owns the output and who gets to decide.",
    "stages": [
      "Reclaim Value",
      "Start Creating",
      "Discover AI's Power",
      "Unhook Identity"
    ],
    "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a20a739ac75b76282f7cc99/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds",
    "stories": [
      {
        "title": "AI Agents Put Creative Control Back on the Table",
        "url": "https://www.forbes.com/sites/ronschmelzer/2026/06/03/ai-agents-put-creative-control-back-on-the-table/",
        "source": "forbes.com",
        "published": "",
        "summary": "AI agents shift the conversation from content generation to delegation. If tools can plan and act, then creative control becomes the central question: who sets the intention, who approves the output, and who remains accountable?",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a20a739ac75b76282f7cc99/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds",
        "stages": [
          "Start Creating",
          "Reclaim Value"
        ],
        "keyPoints": [
          "AI agents raise the stakes from making assets to managing autonomous workflows.",
          "Creative control depends on human direction, review, and boundaries.",
          "This is Start Creating with a Reclaim Value backbone: agency sits in judgment, not button-pushing."
        ]
      },
      {
        "title": "The Creator Act: Protection Artists Need in the Age of AI",
        "url": "https://blog.adobe.com/en/publish/2026/06/02/the-creator-act-protection-artists-need-age-of-ai",
        "source": "blog.adobe.com",
        "published": "",
        "summary": "Adobe's Creator Act frame points to a simple truth: creators cannot repurpose themselves if their work can be absorbed without consent or compensation. Protection is not anti-AI. It is part of making AI adoption livable for humans.",
        "imageUrl": "https://blog.adobe.com/en/publish/2026/06/02/media_1b491d2d3d60132a30441b36aba2191fe7fc7a2e5.png?width=1200&format=pjpg&optimize=medium",
        "stages": [
          "Reclaim Value",
          "Start Creating"
        ],
        "keyPoints": [
          "The creator protection conversation is moving into policy and platform design.",
          "Consent, attribution, and compensation are becoming core AI issues.",
          "TGR relevance: Reclaim Value means defending the human work that trained the machine."
        ]
      },
      {
        "title": "Commerce Department Announces $25 Million For AI Upskilling Initiative",
        "url": "https://www.forbes.com/sites/shalinjyotishi/2026/06/01/commerce-department-announces-25-million-for-ai-upskilling-initiative/",
        "source": "forbes.com",
        "published": "",
        "summary": "Upskilling funding is a sign that AI readiness is becoming public infrastructure. The question is whether these programs teach tools in isolation or help people connect AI capability to identity, value, and purpose.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a1cf9180c213ac369150d21/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds",
        "stages": [
          "Discover AI's Power",
          "Unhook Identity"
        ],
        "keyPoints": [
          "Government-backed AI training signals that readiness is now a workforce priority.",
          "Tool training is useful, but incomplete without a human framework for change.",
          "This is Discover AI's Power after Unhook Identity: learn the tools without becoming the tool."
        ]
      },
      {
        "title": "34,000 Small Businesses Said AI Is Working. The Data Says Otherwise.",
        "url": "https://www.forbes.com/sites/terdawn-deboe/2026/05/29/34000-small-businesses-said-ai-is-working-the-data-says-otherwise/",
        "source": "forbes.com",
        "published": "",
        "summary": "Small-business AI enthusiasm can hide a harder operational truth: adoption is not the same as impact. The useful question is not whether a company tried AI. It is whether AI changed the quality, economics, or originality of the work.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a1a22a809d983793369bc09/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds",
        "stages": [
          "Discover AI's Power",
          "Reclaim Value"
        ],
        "keyPoints": [
          "Self-reported AI success may not match measurable business outcomes.",
          "Small businesses need clearer ways to connect AI use to real value creation.",
          "TGR relevance: Discover AI's Power requires experimentation, but Reclaim Value tells you what to measure."
        ]
      },
      {
        "title": "Epidemic Sound's Creator Economy Report: Human Creativity Will Define Who Succeeds",
        "url": "https://corporate.epidemicsound.com/press-and-media/press-releases/2026/ai-is-changing-how-creators-work-but-control-and-human-creativity-will-define-who-succeeds-epidemic-sound-unveils-the-future-of-the-creator-economy-report-2026/",
        "source": "corporate.epidemicsound.com",
        "published": "",
        "summary": "The creator economy signal is reassuring and demanding at the same time: human creativity still matters, but generic output will get cheaper by the day. Creators win by becoming more themselves, not by outsourcing their taste.",
        "imageUrl": "",
        "stages": [
          "Start Creating",
          "Reclaim Value"
        ],
        "keyPoints": [
          "The report frames human creativity and control as differentiators in an AI-saturated market.",
          "Creators need to protect their voice while using tools that can multiply output.",
          "This is Start Creating from a reclaimed center: more output only matters if it carries real taste."
        ]
      }
    ],
    "sourceStatus": "draft_html"
  },
  "2026-06-04-daily-tgr-signal": {
    "date": "2026-06-04",
    "title": "Creativity Moves Upstream",
    "slug": "2026-06-04-daily-tgr-signal",
    "pattern": "The signal is that creativity is becoming more valuable, not less, but it is changing location. As AI absorbs more execution, human advantage moves upstream into taste, judgment, problem selection, and the courage to make something that actually matters.",
    "stages": [
      "Reclaim Value",
      "Unhook Identity",
      "Find Your Purpose",
      "Start Creating",
      "Discover AI's Power"
    ],
    "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a11204aa488ec8b473b57df/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
    "stories": [
      {
        "title": "AI Isn't Replacing Creativity. It's Moving It Upstream.",
        "url": "https://www.forbes.com/sites/cathyrubin/2026/05/26/ai-isnt-replacing-creativity-its-moving-it-upstream/",
        "source": "forbes.com",
        "published": "",
        "summary": "This is the cleanest articulation of the creative shift: AI does not remove the need for creativity, it changes where creativity lives. The person who can define the problem, shape the brief, and judge the output becomes more important, not less.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a11204aa488ec8b473b57df/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Start Creating",
          "Reclaim Value"
        ],
        "keyPoints": [
          "AI compresses execution, which makes upstream creative judgment more valuable.",
          "The human edge is taste, framing, intent, and the ability to know what good is.",
          "TGR relevance: Start Creating now means directing systems, not just producing assets by hand."
        ]
      },
      {
        "title": "Will the AI Economy Create a Permanent Underclass?",
        "url": "https://www.theguardian.com/business/2026/jun/02/will-the-ai-economy-create-a-permanent-underclass",
        "source": "theguardian.com",
        "published": "",
        "summary": "The underclass question is the hard edge of the AI economy: productivity gains do not automatically translate into human flourishing. Without new paths to agency, the people displaced by systems may be told to adapt after the value has already moved elsewhere.",
        "imageUrl": "https://i.guim.co.uk/img/media/1fe5f1ddb95275c40b568819f804bd506f87e7b5/1129_0_6630_5304/master/6630.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&precrop=40:21,offset-x50,offset-y0&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctb3Bpb25zLnBuZw&enable=upscale&s=4b31a47b53bb90937f11090168a18996",
        "stages": [
          "Unhook Identity",
          "Find Your Purpose"
        ],
        "keyPoints": [
          "AI could deepen inequality if ownership and opportunity remain concentrated.",
          "The story forces the labor question beyond reskilling slogans.",
          "This is Unhook Identity plus Find Your Purpose: people need a new foundation, not just a new course link."
        ]
      },
      {
        "title": "AI Will Reshape More Jobs Than It Replaces",
        "url": "https://www.bcg.com/publications/2026/ai-will-reshape-more-jobs-than-it-replaces",
        "source": "bcg.com",
        "published": "",
        "summary": "The more honest labor story is not a clean replacement count. It is a reshaping of tasks, teams, expectations, and value inside millions of roles. That can be hopeful, but only if people get a map for the transition.",
        "imageUrl": "https://web-assets.bcg.com/dims4/default/781d637/2147483647/strip/true/crop/2880x1512+0+0/resize/1200x630!/format/webp/quality/90/?url=http%3A%2F%2Fboston-consulting-group-brightspot.s3.amazonaws.com%2F01%2F6b%2F6458a17e4f19b3f8b0ce0f2909ca%2Fai-will-reshape-more-jobs-than-it-replaces-hero.jpg",
        "stages": [
          "Reclaim Value",
          "Unhook Identity"
        ],
        "keyPoints": [
          "Job change will often arrive as task redesign before full displacement.",
          "Workers need to understand which parts of their work are becoming automated and which parts become more valuable.",
          "TGR relevance: Reclaim Value is the bridge between fear and practical adaptation."
        ]
      },
      {
        "title": "Is AI Prompting a Creative Renaissance?",
        "url": "https://insight.kellogg.northwestern.edu/article/is-ai-prompting-a-creative-renaissance",
        "source": "insight.kellogg.northwestern.edu",
        "published": "",
        "summary": "A creative renaissance is possible, but it will not happen automatically because the tools got better. It happens when more people use AI to explore, combine, and express ideas they would not have had the time or means to make before.",
        "imageUrl": "https://cdn.craft.cloud/019d3066-3548-718e-af5b-3333a57196ee/assets/content/uploads/Full_0326_AI_Job_Threats.jpg?fit=contain&height=630&width=1200&s=JaRYTH4Qx4EH_xfmWlTOgNJ7M5CM_PKvnJLuQuw8WH0",
        "stages": [
          "Discover AI's Power",
          "Start Creating"
        ],
        "keyPoints": [
          "AI can expand creative participation if people use it as an instrument rather than a shortcut.",
          "The renaissance depends on human curiosity, taste, and willingness to play.",
          "This is Discover AI's Power leading into Start Creating."
        ]
      },
      {
        "title": "10 Human Skills Likely to Protect Your Job From AI",
        "url": "https://www.forbes.com/sites/bryanrobinson/2026/06/04/10-human-skills-likely-to-protect-your-job-from-ai-per-click-finder/",
        "source": "forbes.com",
        "published": "",
        "summary": "Lists of human skills matter because they help people name what remains valuable when tools change. The danger is treating them as motivational wallpaper instead of a real inventory of judgment, trust, communication, and adaptability.",
        "imageUrl": "https://imageio.forbes.com/specials-images/imageserve/6a1095d86b6918320ec56b91/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        "stages": [
          "Reclaim Value",
          "Find Your Purpose"
        ],
        "keyPoints": [
          "The story points toward durable skills that automation struggles to absorb cleanly.",
          "People need language for the human layer beneath their current tasks.",
          "This is Reclaim Value and Find Your Purpose: know what you bring, then aim it somewhere useful."
        ]
      }
    ],
    "sourceStatus": "sent_html"
  }
} as const;
